### ISSUE TITLE
Do not require manual initialization of data

### ISSUE THREAD

**Issue by maxaudron** [r-lmr/lmrdashboard#38]
The backend currently requires some manual setup to be done in the database.
Make the backend create all needed tables etc.

**Comment by LoLei** [comment]
https://github.com/aboft/lmrdashboard/blob/docker-compose/docker-compose.yml#L12

**Comment by aboft** [comment]
addressed with issue [#41 ](https://github.com/aboft/lmrdashboard/pull/41)
